# golang Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-app
  namespace: apiwars
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-app
  template:
    metadata:
      labels:
        app: golang-app
    spec:
      containers:
        - name: golang-app
          image: registry.waxmaker.app/apiwars/golang:0.0.1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "1"
              memory: "512Mi"

# golang service
---
apiVersion: v1
kind: Service
metadata:
  name: golang-app
  namespace: apiwars
spec:
  type: NodePort
  selector:
    app: golang-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30999

# python Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: apiwars
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: registry.waxmaker.app/apiwars/python:0.0.1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "1"
              memory: "512Mi"
# python service
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: apiwars
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30998
